services:
  icp_algorithm:
    container_name: icp-pcd
    build: .
    environment:
      DISPLAY: $DISPLAY
    # image: icp-pcd  # Replace with the name of the Docker image for your ICP algorithm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./Tools:/Tools
      # - ./docker-compose.yaml:/docker-compose.yaml
      # - ./Dockerfile:/Dockerfile
      # - ./datasets:/datasets  # Links the local 'datasets' folder to '/datasets' in the container
    command: ["./run.sh"]  # Replace with the command to run the ICP algorithm
